before_script:
  - "sh -e /etc/init.d/xvfb start"
env:
  - DB=sqlite
script:
  - "export DISPLAY=:99.0"
  - "alias set_gemfile='export BUNDLE_GEMFILE=\"`pwd`/Gemfile\"'"
  - "cd core; set_gemfile; bundle install --quiet; bundle exec rake test_app; bundle exec rspec spec/requests/admin/configuration/states_spec.rb"

branches:
  only:
    - duplicate_failing_state_spec
rvm:
  - 1.9.3
